---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
aliases:
  tenna/image_tag: &image_tag "v1.2.0"
metadata:
  name: tutorial-memcached-bundle
  namespace: demo
  annotations:
    tenna/test: "does this hurt"
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 3.2.0